dist: trusty
sudo: required
language: java
jdk: oraclejdk8
addons:
    sonarqube:
        organization: "viktorc-github"
        token:
            secure: $SONAR_TOKEN
install: true
script: mvn clean install jacoco:report coveralls:report sonar:sonar
cache:
    directories:
        - $HOME/.m2
        - $HOME/.sonar/cache
notifications:
    email: false
deploy:
    provider: pages
    local_dir: $TRAVIS_BUILD_DIR/ViktorC/PSPPool/docs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
deploy:
    provider: releases
    api_key: $GITHUB_TOKEN
    file: $TRAVIS_BUILD_DIR/ViktorC/PSPPool/target/pspp*.jar
    skip_cleanup: true
    on:
        tags: true
