dist: trusty
sudo: required
language: java
jdk: oraclejdk8
addons:
    sonarqube:
        organization: "viktorc-github"
        token:
            secure: $SONAR_TOKEN
install: true
script:
    - echo $PWD
    - find -name build-script.sh
    - sudo chmod 4777 build-script.sh
    - sudo /home/travis/build/ViktorC/PSPPool/build-script.sh
cache:
    directories:
        - $HOME/.m2
        - $HOME/.sonar/cache
notifications:
    email: false
