dist: trusty
sudo: required
jdk: oraclejdk8
addons:
    sonarqube:
        organization: "viktorc-github"
        token:
            secure: $SONAR_TOKEN
install: true
script: mvn clean install sonar:sonar
cache:
    directories:
        - $HOME/.m2
        - $HOME/.sonar/cache
notifications:
    email: false
