dist: trusty
sudo: required
language: java
jdk: oraclejdk8
addons:
    sonarqube:
        organization: "viktorc-github"
        token:
            secure: $SONAR_TOKEN
install: true
script:
    - sudo chmod 777 /home/travis/build/ViktorC/PSPPool/src/test/resources/net/viktorc/pspp/linux/test
    - /home/travis/build/ViktorC/PSPPool/src/test/resources/net/viktorc/pspp/linux/test
    - mvn clean install jacoco:report coveralls:report sonar:sonar
cache:
    directories:
        - $HOME/.m2
        - $HOME/.sonar/cache
notifications:
    email: false
deploy:
    provider: pages
    local_dir: /home/travis/build/ViktorC/PSPPool/docs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
