dist: trusty
sudo: required
language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
addons:
  sonarqube:
    organization: "viktorc-github"
    token: $SONAR_TOKEN
install: true
script: mvn clean jacoco:prepare-agent install jacoco:report sonar:sonar
cache:
  directories:
  - $HOME/.m2
  - $HOME/.sonar/cache
notifications:
  email: false
deploy:
  provider: pages
  local_dir: docs
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
