dist: trusty
language: java
jdk: oraclejdk8
addons:
    sonarqube:
        organization: "viktorc"
        token:
            secure: $SONAR_TOKEN
script:
  - mvn clean install sonar:sonar
cache:
    directories:
    - $HOME/.m2
