dist: trusty
sudo: required
language: java
jdk: oraclejdk8
addons:
    sonarqube:
        organization: "viktorc-github"
        token:
            secure: $SONAR_TOKEN
install: true
before_script: sudo su
script:
    - chmod -R 777 /home
    - ls -l /home/travis/build/ViktorC/PSPPool/target/test-classes/net/viktorc/pspp/linux/test
    - mvn clean install jacoco:report coveralls:report sonar:sonar
cache:
    directories:
        - $HOME/.m2
        - $HOME/.sonar/cache
notifications:
    email: false
